"""
Streamlit wrapper for the TradingView Lightweight Chart generated by ``chart_tab.generate_chart_html``.
Provides ``render_chart_tab`` which renders UI selectors and embeds the chart.
"""

import streamlit as st

from src.dashboard.chart_tab import generate_chart_html


# Cache data loading – placeholder for future real data fetches
@st.cache_data(show_spinner=False)
def load_chart_data(symbol: str, timeframe: str):
    """Load chart data for the given symbol and timeframe.
    Currently returns ``None`` to trigger synthetic data generation.
    """
    # In a real implementation you would fetch OHLCV data here.
    return

def render_chart_tab():
    """Render the chart tab in Streamlit.
    Includes dropdowns for symbol and timeframe, and embeds the chart HTML.
    """
    col1, col2 = st.columns([1, 1])
    with col1:
        symbol = st.selectbox("Symbol", options=["EURUSD", "GBPUSD", "USDJPY", "XAUUSD", "BTCUSD", "ETHUSD", "SPY", "QQQ", "AAPL"], index=0)
    with col2:
        timeframe = st.selectbox("Timeframe", options=["1m", "5m", "15m", "1h", "4h", "1D"], index=1)
    data = load_chart_data(symbol, timeframe)
    chart_html = generate_chart_html(symbol=symbol, timeframe=timeframe, data=data)
    st.components.v1.html(chart_html, height=700, scrolling=True)

if __name__ == "__main__":
    st.set_page_config(layout="centered", page_title="Trading Chart")
    render_chart_tab()
