from __future__ import annotations

from prometheus_client import CollectorRegistry, Counter, Gauge, Histogram, generate_latest

# Custom registry for isolation
REGISTRY = CollectorRegistry()


# ============================================
# METRICS DEFINITIONS
# ============================================

# Counters
orders_total = Counter(
    'forex_orders_total',
    'Total number of orders placed',
    ['strategy', 'symbol', 'side', 'status', 'broker'],
    registry=REGISTRY,
)

signals_total = Counter(
    'forex_signals_total',
    'Total number of signals generated',
    ['strategy', 'symbol', 'signal_type', 'direction'],
    registry=REGISTRY,
)

trades_total = Counter(
    'forex_trades_total',
    'Total number of completed trades',
    ['strategy', 'symbol', 'direction', 'exit_reason'],
    registry=REGISTRY,
)

errors_total = Counter(
    'forex_errors_total',
    'Total number of errors',
    ['component', 'error_type'],
    registry=REGISTRY,
)

circuit_breaker_triggers = Counter(
    'forex_circuit_breaker_triggers_total',
    'Total circuit breaker triggers',
    ['breaker_type'],
    registry=REGISTRY,
)

alerts_sent = Counter(
    'forex_alerts_sent_total',
    'Total alerts sent',
    ['channel', 'level'],
    registry=REGISTRY,
)

# Histograms
order_latency = Histogram(
    'forex_order_latency_seconds',
    'Order placement latency',
    ['broker', 'order_type'],
    buckets=[0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0],
    registry=REGISTRY,
)

signal_generation_latency = Histogram(
    'forex_signal_generation_latency_seconds',
    'Signal generation latency',
    ['strategy'],
    buckets=[0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0],
    registry=REGISTRY,
)

data_ingestion_latency = Histogram(
    'forex_data_ingestion_latency_seconds',
    'Data ingestion latency',
    ['source', 'symbol'],
    buckets=[0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0],
    registry=REGISTRY,
)

backtest_duration = Histogram(
    'forex_backtest_duration_seconds',
    'Backtest execution duration',
    ['strategy'],
    buckets=[1, 5, 10, 30, 60, 300, 600, 1800, 3600],
    registry=REGISTRY,
)

# Gauges
portfolio_equity = Gauge(
    'forex_portfolio_equity',
    'Current portfolio equity',
    ['currency'],
    registry=REGISTRY,
)

portfolio_unrealized_pnl = Gauge(
    'forex_portfolio_unrealized_pnl',
    'Current unrealized P&L',
    ['currency'],
    registry=REGISTRY,
)

portfolio_realized_pnl = Gauge(
    'forex_portfolio_realized_pnl',
    'Current realized P&L',
    ['currency'],
    registry=REGISTRY,
)

portfolio_drawdown = Gauge(
    'forex_portfolio_drawdown_pct',
    'Current drawdown percentage',
    registry=REGISTRY,
)

portfolio_max_drawdown = Gauge(
    'forex_portfolio_max_drawdown_pct',
    'Maximum drawdown percentage',
    registry=REGISTRY,
)

open_positions = Gauge(
    'forex_open_positions',
    'Number of open positions',
    ['strategy', 'symbol', 'direction'],
    registry=REGISTRY,
)

position_volume = Gauge(
    'forex_position_volume',
    'Position volume',
    ['strategy', 'symbol', 'direction'],
    registry=REGISTRY,
)

position_unrealized_pnl = Gauge(
    'forex_position_unrealized_pnl',
    'Position unrealized P&L',
    ['strategy', 'symbol'],
    registry=REGISTRY,
)

margin_used = Gauge(
    'forex_margin_used',
    'Margin currently used',
    ['currency', 'broker'],
    registry=REGISTRY,
)

free_margin = Gauge(
    'forex_free_margin',
    'Free margin available',
    ['currency', 'broker'],
    registry=REGISTRY,
)

margin_level = Gauge(
    'forex_margin_level_pct',
    'Margin level percentage',
    ['broker'],
    registry=REGISTRY,
)

leverage = Gauge(
    'forex_leverage',
    'Current leverage',
    ['broker'],
    registry=REGISTRY,
)

var_95 = Gauge(
    'forex_var_95',
    'Value at Risk 95%',
    ['currency'],
    registry=REGISTRY,
)

var_99 = Gauge(
    'forex_var_99',
    'Value at Risk 99%',
    ['currency'],
    registry=REGISTRY,
)

expected_shortfall_95 = Gauge(
    'forex_expected_shortfall_95',
    'Expected Shortfall 95%',
    ['currency'],
    registry=REGISTRY,
)

expected_shortfall_99 = Gauge(
    'forex_expected_shortfall_99',
    'Expected Shortfall 99%',
    ['currency'],
    registry=REGISTRY,
)

max_correlation = Gauge(
    'forex_max_correlation',
    'Maximum position correlation',
    registry=REGISTRY,
)

sector_exposure = Gauge(
    'forex_sector_exposure_pct',
    'Sector exposure percentage',
    ['sector'],
    registry=REGISTRY,
)

# Strategy metrics
strategy_signals_generated = Gauge(
    'forex_strategy_signals_generated',
    'Total signals generated by strategy',
    ['strategy_id'],
    registry=REGISTRY,
)

strategy_active = Gauge(
    'forex_strategy_active',
    'Strategy active status (1=active, 0=inactive)',
    ['strategy_id'],
    registry=REGISTRY,
)

strategy_error_count = Gauge(
    'forex_strategy_error_count',
    'Strategy error count',
    ['strategy_id'],
    registry=REGISTRY,
)

strategy_uptime = Gauge(
    'forex_strategy_uptime_seconds',
    'Strategy uptime in seconds',
    ['strategy_id'],
    registry=REGISTRY,
)

# Risk metrics
daily_loss = Gauge(
    'forex_daily_loss_pct',
    'Daily loss percentage',
    registry=REGISTRY,
)

weekly_loss = Gauge(
    'forex_weekly_loss_pct',
    'Weekly loss percentage',
    registry=REGISTRY,
)

monthly_loss = Gauge(
    'forex_monthly_loss_pct',
    'Monthly loss percentage',
    registry=REGISTRY,
)

consecutive_losses = Gauge(
    'forex_consecutive_losses',
    'Number of consecutive losing trades',
    ['strategy'],
    registry=REGISTRY,
)

# Data metrics
market_data_age = Gauge(
    'forex_market_data_age_seconds',
    'Age of latest market data',
    ['source', 'symbol', 'timeframe'],
    registry=REGISTRY,
)

data_ingestion_rate = Gauge(
    'forex_data_ingestion_rate',
    'Data ingestion rate (bars/second)',
    ['source'],
    registry=REGISTRY,
)

# System metrics
component_status = Gauge(
    'forex_component_status',
    'Component health status (1=healthy, 0=unhealthy)',
    ['component'],
    registry=REGISTRY,
)

api_requests_total = Counter(
    'forex_api_requests_total',
    'Total API requests',
    ['method', 'endpoint', 'status'],
    registry=REGISTRY,
)

api_request_duration = Histogram(
    'forex_api_request_duration_seconds',
    'API request duration',
    ['method', 'endpoint'],
    buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0],
    registry=REGISTRY,
)

websocket_connections = Gauge(
    'forex_websocket_connections',
    'Active WebSocket connections',
    ['endpoint'],
    registry=REGISTRY,
)

# Database metrics
db_connections_active = Gauge(
    'forex_db_connections_active',
    'Active database connections',
    ['database'],
    registry=REGISTRY,
)

db_connections_idle = Gauge(
    'forex_db_connections_idle',
    'Idle database connections',
    ['database'],
    registry=REGISTRY,
)

db_query_duration = Histogram(
    'forex_db_query_duration_seconds',
    'Database query duration',
    ['database', 'query_type'],
    buckets=[0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0],
    registry=REGISTRY,
)

# Cache metrics
cache_hits = Counter(
    'forex_cache_hits_total',
    'Cache hits',
    ['cache_type'],
    registry=REGISTRY,
)

cache_misses = Counter(
    'forex_cache_misses_total',
    'Cache misses',
    ['cache_type'],
    registry=REGISTRY,
)

# Message queue metrics
messages_published = Counter(
    'forex_messages_published_total',
    'Messages published',
    ['topic'],
    registry=REGISTRY,
)

messages_consumed = Counter(
    'forex_messages_consumed_total',
    'Messages consumed',
    ['topic', 'consumer'],
    registry=REGISTRY,
)

message_queue_lag = Gauge(
    'forex_message_queue_lag',
    'Message queue lag',
    ['topic'],
    registry=REGISTRY,
)


# ============================================
# METRICS COLLECTOR CLASS
# ============================================

class MetricsCollector:
    """Centralized metrics collection and management."""

    def __init__(self):
        self._initialized = False

    def init_metrics(self) -> None:
        """Initialize metrics with default values."""
        if self._initialized:
            return

        # Set initial values
        component_status.labels(component="api").set(1)
        component_status.labels(component="data_ingestion").set(1)
        component_status.labels(component="strategy_engine").set(1)
        component_status.labels(component="risk_manager").set(1)
        component_status.labels(component="execution_engine").set(1)
        component_status.labels(component="dashboard").set(1)

        self._initialized = True

    def get_metrics(self) -> bytes:
        """Get metrics in Prometheus format."""
        return generate_latest(REGISTRY)

    def get_content_type(self) -> str:
        """Get Prometheus content type."""
        from prometheus_client import CONTENT_TYPE_LATEST
        return CONTENT_TYPE_LATEST

    # ============================================
    # RECORDING METHODS
    # ============================================

    def record_order(
        self,
        strategy: str,
        symbol: str,
        side: str,
        status: str,
        broker: str,
        latency: float | None = None,
    ) -> None:
        """Record order metrics."""
        orders_total.labels(
            strategy=strategy,
            symbol=symbol,
            side=side,
            status=status,
            broker=broker,
        ).inc()

        if latency is not None:
            order_latency.labels(broker=broker, order_type=side).observe(latency)

    def record_signal(
        self,
        strategy: str,
        symbol: str,
        signal_type: str,
        direction: str,
        latency: float | None = None,
    ) -> None:
        """Record signal metrics."""
        signals_total.labels(
            strategy=strategy,
            symbol=symbol,
            signal_type=signal_type,
            direction=direction,
        ).inc()

        if latency is not None:
            signal_generation_latency.labels(strategy=strategy).observe(latency)

    def record_trade(
        self,
        strategy: str,
        symbol: str,
        direction: str,
        exit_reason: str,
    ) -> None:
        """Record trade metrics."""
        trades_total.labels(
            strategy=strategy,
            symbol=symbol,
            direction=direction,
            exit_reason=exit_reason,
        ).inc()

    def record_error(self, component: str, error_type: str) -> None:
        """Record error."""
        errors_total.labels(component=component, error_type=error_type).inc()

    def record_circuit_breaker(self, breaker_type: str) -> None:
        """Record circuit breaker trigger."""
        circuit_breaker_triggers.labels(breaker_type=breaker_type).inc()

    def record_alert(self, channel: str, level: str) -> None:
        """Record alert sent."""
        alerts_sent.labels(channel=channel, level=level).inc()

    def update_equity(self, equity: float, currency: str = "USD") -> None:
        """Update equity gauge."""
        portfolio_equity.labels(currency=currency).set(equity)

    def update_pnl(self, unrealized: float, realized: float, currency: str = "USD") -> None:
        """Update P&L gauges."""
        portfolio_unrealized_pnl.labels(currency=currency).set(unrealized)
        portfolio_realized_pnl.labels(currency=currency).set(realized)

    def update_drawdown(self, current: float, max_dd: float) -> None:
        """Update drawdown gauges."""
        portfolio_drawdown.set(current)
        portfolio_max_drawdown.set(max_dd)

    def update_position(
        self,
        strategy: str,
        symbol: str,
        direction: str,
        volume: float,
        unrealized_pnl: float,
    ) -> None:
        """Update position metrics."""
        open_positions.labels(
            strategy=strategy,
            symbol=symbol,
            direction=direction,
        ).set(1 if volume > 0 else 0)

        position_volume.labels(
            strategy=strategy,
            symbol=symbol,
            direction=direction,
        ).set(volume)

        position_unrealized_pnl.labels(
            strategy=strategy,
            symbol=symbol,
        ).set(unrealized_pnl)

    def remove_position(self, strategy: str, symbol: str, direction: str) -> None:
        """Remove position metrics."""
        open_positions.labels(
            strategy=strategy,
            symbol=symbol,
            direction=direction,
        ).set(0)

        position_volume.labels(
            strategy=strategy,
            symbol=symbol,
            direction=direction,
        ).set(0)

    def update_margin(
        self,
        used: float,
        free: float,
        level: float,
        lev: float,
        currency: str = "USD",
        broker: str = "mt5",
    ) -> None:
        """Update margin metrics."""
        margin_used.labels(currency=currency, broker=broker).set(used)
        free_margin.labels(currency=currency, broker=broker).set(free)
        margin_level.labels(broker=broker).set(level)
        leverage.labels(broker=broker).set(lev)

    def update_var(self, var_95_val: float, var_99_val: float, es_95: float, es_99: float, currency: str = "USD") -> None:
        """Update VaR/ES metrics."""
        var_95.labels(currency=currency).set(var_95_val)
        var_99.labels(currency=currency).set(var_99_val)
        expected_shortfall_95.labels(currency=currency).set(es_95)
        expected_shortfall_99.labels(currency=currency).set(es_99)

    def update_correlation(self, max_corr: float) -> None:
        """Update max correlation."""
        max_correlation.set(max_corr)

    def update_sector_exposure(self, sector: str, exposure: float) -> None:
        """Update sector exposure."""
        sector_exposure.labels(sector=sector).set(exposure)

    def update_strategy_metrics(
        self,
        strategy_id: str,
        signals_generated: int,
        active: bool,
        error_count: int,
        uptime: float,
    ) -> None:
        """Update strategy metrics."""
        strategy_signals_generated.labels(strategy_id=strategy_id).set(signals_generated)
        strategy_active.labels(strategy_id=strategy_id).set(1 if active else 0)
        strategy_error_count.labels(strategy_id=strategy_id).set(error_count)
        strategy_uptime.labels(strategy_id=strategy_id).set(uptime)

    def update_loss_limits(self, daily: float, weekly: float, monthly: float) -> None:
        """Update loss limit metrics."""
        daily_loss.set(daily)
        weekly_loss.set(weekly)
        monthly_loss.set(monthly)

    def update_consecutive_losses(self, strategy: str, count: int) -> None:
        """Update consecutive losses."""
        consecutive_losses.labels(strategy=strategy).set(count)

    def update_data_age(self, source: str, symbol: str, timeframe: str, age: float) -> None:
        """Update market data age."""
        market_data_age.labels(source=source, symbol=symbol, timeframe=timeframe).set(age)

    def update_ingestion_rate(self, source: str, rate: float) -> None:
        """Update data ingestion rate."""
        data_ingestion_rate.labels(source=source).set(rate)

    def update_component_status(self, component: str, healthy: bool) -> None:
        """Update component status."""
        component_status.labels(component=component).set(1 if healthy else 0)

    def record_api_request(self, method: str, endpoint: str, status: int, duration: float) -> None:
        """Record API request."""
        api_requests_total.labels(method=method, endpoint=endpoint, status=str(status)).inc()
        api_request_duration.labels(method=method, endpoint=endpoint).observe(duration)

    def update_websocket_connections(self, endpoint: str, count: int) -> None:
        """Update WebSocket connections."""
        websocket_connections.labels(endpoint=endpoint).set(count)

    def update_db_connections(self, database: str, active: int, idle: int) -> None:
        """Update DB connection metrics."""
        db_connections_active.labels(database=database).set(active)
        db_connections_idle.labels(database=database).set(idle)

    def record_db_query(self, database: str, query_type: str, duration: float) -> None:
        """Record DB query duration."""
        db_query_duration.labels(database=database, query_type=query_type).observe(duration)

    def record_cache_hit(self, cache_type: str) -> None:
        """Record cache hit."""
        cache_hits.labels(cache_type=cache_type).inc()

    def record_cache_miss(self, cache_type: str) -> None:
        """Record cache miss."""
        cache_misses.labels(cache_type=cache_type).inc()

    def record_message_published(self, topic: str) -> None:
        """Record message published."""
        messages_published.labels(topic=topic).inc()

    def record_message_consumed(self, topic: str, consumer: str) -> None:
        """Record message consumed."""
        messages_consumed.labels(topic=topic, consumer=consumer).inc()

    def update_queue_lag(self, topic: str, lag: int) -> None:
        """Update queue lag."""
        message_queue_lag.labels(topic=topic).set(lag)


# Global metrics collector
metrics_collector = MetricsCollector()


def get_metrics_collector() -> MetricsCollector:
    """Get the global metrics collector instance."""
    return metrics_collector