from __future__ import annotations

"""Independent Risk Verifier (V2.2 Section 86 / EAQTS-3189-3208).

Provides a pure‑Python implementation that recomputes risk metrics and compares
them with the primary risk engine results. Any mismatches beyond defined
thresholds cause the verification to fail.
"""

import logging
import math
from dataclasses import asdict, dataclass
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass(slots=True)
class Mismatch:
    metric: str
    primary_value: float
    verifier_value: float
    threshold: float
    exceeds_threshold: bool

    def to_dict(self) -> dict:
        d = asdict(self)
        d["exceeds_threshold"] = self.exceeds_threshold
        return d

@dataclass(slots=True)
class VerificationResult:
    matches: bool
    mismatches: list[Mismatch]
    independent_values: dict[str, float]

    def to_dict(self) -> dict:
        return {
            "matches": self.matches,
            "mismatches": [m.to_dict() for m in self.mismatches],
            "independent_values": self.independent_values,
        }

# ---------------------------------------------------------------------------
# Helper functions – pure mathematics, no external dependencies.
# ---------------------------------------------------------------------------

def _calc_exposure(positions: list[dict[str, Any]]) -> float:
    # exposure = sum(|size| * price * contract_size)
    exposure = 0.0
    for p in positions:
        size = abs(p.get("size", 0.0))
        price = p.get("price", 0.0)
        contract = p.get("contract_size", 1.0)
        exposure += size * price * contract
    return exposure

def _calc_leverage(exposure: float, equity: float) -> float:
    if equity == 0:
        return math.inf
    return exposure / equity

def _calc_margin(positions: list[dict[str, Any]], leverage: float) -> float:
    total_val = sum(p.get("size", 0.0) * p.get("price", 0.0) * p.get("contract_size", 1.0) for p in positions)
    if leverage == 0:
        return 0.0
    return total_val / leverage

def _calc_symbol_risk(position: dict[str, Any]) -> float:
    # VaR‑style risk: position_value * volatility * z_score
    size = abs(position.get("size", 0.0))
    price = position.get("price", 0.0)
    contract = position.get("contract_size", 1.0)
    volatility = position.get("volatility", 0.0)
    z = position.get("z_score", 2.33)  # 99% confidence default
    return size * price * contract * volatility * z

def _calc_portfolio_risk(symbol_risks: list[float]) -> float:
    # Simplified: sqrt(sum(var_i^2)). Treat each symbol risk as standard deviation.
    variance_sum = sum(r ** 2 for r in symbol_risks)
    return math.sqrt(variance_sum)

def _calc_concentration(positions: list[dict[str, Any]], total_exposure: float) -> float:
    if total_exposure == 0:
        return 0.0
    max_exposure = 0.0
    for p in positions:
        size = abs(p.get("size", 0.0))
        price = p.get("price", 0.0)
        contract = p.get("contract_size", 1.0)
        exp = size * price * contract
        max_exposure = max(max_exposure, exp)
    return max_exposure / total_exposure

# ---------------------------------------------------------------------------
# Main verification function
# ---------------------------------------------------------------------------

def verify(primary_results: dict[str, float], context: dict[str, Any]) -> VerificationResult:
    """Independently recompute risk metrics and compare to primary engine.

    Parameters
    ----------
    primary_results:
        Mapping of metric name to value generated by the primary risk engine.
    context:
        Must contain ``positions`` (list of dicts with size, price, contract_size,
        volatility, z_score) and ``equity`` (float).

    Returns
    -------
    VerificationResult
        ``matches`` is ``True`` only if all independent values are within the
        configured tolerance thresholds.
    """
    positions = context.get("positions", [])
    equity = context.get("equity", 0.0)
    if not positions:
        logger.warning("Risk verifier invoked with empty positions list")

    # Compute independent metrics
    exposure = _calc_exposure(positions)
    leverage = _calc_leverage(exposure, equity)
    margin = _calc_margin(positions, leverage)
    symbol_risks = [_calc_symbol_risk(p) for p in positions]
    portfolio_risk = _calc_portfolio_risk(symbol_risks)
    concentration = _calc_concentration(positions, exposure)

    independent = {
        "exposure": exposure,
        "leverage": leverage,
        "margin": margin,
        "portfolio_risk": portfolio_risk,
        "concentration": concentration,
    }

    # Define per‑metric tolerance thresholds (relative to equity where appropriate)
    thresholds = {
        "exposure": 0.001 * equity,  # 0.1% of equity
        "leverage": 0.02,  # absolute difference of 0.02 (2% points)
        "margin": 0.001 * equity,
        "portfolio_risk": 0.001 * equity,
        "concentration": 0.01,  # 1% absolute concentration difference
    }

    mismatches: list[Mismatch] = []
    matches = True
    for metric, verifier_val in independent.items():
        primary_val = primary_results.get(metric)
        if primary_val is None:
            # Missing primary metric – treat as mismatch.
            mismatches.append(Mismatch(metric, None, verifier_val, thresholds[metric], True))
            matches = False
            continue
        diff = abs(primary_val - verifier_val)
        thresh = thresholds[metric]
        exceeds = diff > thresh
        if exceeds:
            matches = False
        mismatches.append(Mismatch(metric, primary_val, verifier_val, thresh, exceeds))

    result = VerificationResult(matches, mismatches, independent)
    if matches:
        logger.info("Risk verification succeeded – all metrics within tolerance")
    else:
        logger.warning("Risk verification mismatches detected: %s", [m.metric for m in mismatches if m.exceeds_threshold])
    return result
